### ISSUE TITLE
Could not find the following item: XXXX

### ISSUE THREAD

**Issue by SanderVeeken** [2Lynk/OneBlock#4]
On oneblock level 4 "Farming Soil and Plants", oneblock produces an error:
"oneblock: Could not find the following item: SEEDS"
Only got the notice once, but no regular seeds spawned during the entire level.

On oneblock level 5 "Nether Basics", oneblock produces an error:
"oneblock: Could not find the following item: NETHER RACK"
Multiple times.

On oneblock level 5 "Nether Basics", oneblock produces an error:
"oneblock: Could not find the following item: QUARTZ ORE"
Multiple times.

Not running any mods that should interfere, only Iris, Sodium, Lithium and Xaero's map. Fabric api 0.96.0 (specified for 1.20.4).

**Comment by SanderVeeken** [comment]
Actually could it be as simple as the names being wrong? I couldn't quickly find in the code how you link "your" block names with the ones the Fabric API uses but the standard Minecraft Java Minecraft ID names for these are
wheat_seeds, netherrack and nether_quartz_ore. The other names seem to match at first sight.

**Comment by 2Lynk** [comment]
Heya,

Probably is a naming issue.
For each item listed as a possible drop I check if the item exists with a loop over the Block. or Item. objects (depending on the type ofcourse).

This would give issues but it should show in the console. You should find an error in the log when the mod tries and fails to find the right block or item.
Did you check the console?

**Comment by SanderVeeken** [comment]
The console says exactly what I said above:
oneblock: Could not find the following item: SEEDS

In your code the only place where that happens is in the name check. I'm a little confused why the names are different from the standard minecraft xxx_xxx format but I changed the names in the JSON and now "NETHER QUARTZ ORE" generates and I don't get an error.

**Comment by ebb010** [comment]
Hey sander, try to change the names on the archives of mid for these here: WHEAT SEEDS, NETHER QUARTZ ORE, NETHERRACK, this may solve your problem, for me this works.
